package Frames;

import Alumnos.BuscarAlu;
import Clases.NuevaClase;
import Profesores.NuevoProf;
import Alumnos.Nuevoalu;
import Clases.ElimClas;
import Alumnos.VerAlu;
import Clases.VerClas;
import Pagos.busfich;
import Profesores.VerProfe;
import Profesores.busqueda;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import java.net.URL;
import javax.swing.ImageIcon;



/**
 *
 * @author obedn
 */
public class Inicio extends javax.swing.JFrame {
     VerProfe verpr=new VerProfe();
     
    /**
     * Creates new form Inicio
     */
    public Inicio()  {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url= getClass().getResource("/Imagenes/logo.png");
        ImageIcon img= new ImageIcon(url);
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon=new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        Image imagen=icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics e){
                e.drawImage(imagen,0,0,getWidth(),getHeight(),this);

            }
        };
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMclas = new javax.swing.JMenu();
        jMclasNueva = new javax.swing.JMenuItem();
        jMclasVer = new javax.swing.JMenuItem();
        jMclasEliminar = new javax.swing.JMenuItem();
        jMprof = new javax.swing.JMenu();
        jMprofAnadir = new javax.swing.JMenuItem();
        jMprofVer = new javax.swing.JMenuItem();
        jMalum = new javax.swing.JMenu();
        jMalumAnadir = new javax.swing.JMenuItem();
        jMalumClases = new javax.swing.JMenuItem();
        jMalumVer = new javax.swing.JMenuItem();
        jMhora = new javax.swing.JMenu();
        jMhoraEditar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foro cultural CedArte");
        setUndecorated(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1389, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jMclas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_add.png"))); // NOI18N
        jMclas.setText("Clases");
        jMclas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMclasNueva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMclasNueva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMclasNueva.setText("Nueva");
        jMclasNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMclasNuevaActionPerformed(evt);
            }
        });
        jMclas.add(jMclasNueva);

        jMclasVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMclasVer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMclasVer.setText("Ver/Editar");
        jMclasVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMclasVerActionPerformed(evt);
            }
        });
        jMclas.add(jMclasVer);

        jMclasEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMclasEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMclasEliminar.setText("Eliminar");
        jMclasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMclasEliminarActionPerformed(evt);
            }
        });
        jMclas.add(jMclasEliminar);

        jMenuBar1.add(jMclas);

        jMprof.setBackground(new java.awt.Color(204, 255, 0));
        jMprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Profesor.png"))); // NOI18N
        jMprof.setText("Profesores");
        jMprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMprofAnadir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMprofAnadir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMprofAnadir.setText("Añadir Profesor");
        jMprofAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMprofAnadirActionPerformed(evt);
            }
        });
        jMprof.add(jMprofAnadir);

        jMprofVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMprofVer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMprofVer.setText("Ver/editar");
        jMprofVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMprofVerActionPerformed(evt);
            }
        });
        jMprof.add(jMprofVer);

        jMenuBar1.add(jMprof);

        jMalum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jMalum.setText("Alumnos");
        jMalum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMalumAnadir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMalumAnadir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMalumAnadir.setText("Añadir");
        jMalumAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumAnadirActionPerformed(evt);
            }
        });
        jMalum.add(jMalumAnadir);

        jMalumClases.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMalumClases.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMalumClases.setText("Asignar clases");
        jMalumClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumClasesActionPerformed(evt);
            }
        });
        jMalum.add(jMalumClases);

        jMalumVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMalumVer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMalumVer.setText("Eliminar");
        jMalumVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumVerActionPerformed(evt);
            }
        });
        jMalum.add(jMalumVer);

        jMenuBar1.add(jMalum);

        jMhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clock.png"))); // NOI18N
        jMhora.setText("Horario");
        jMhora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMhoraEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMhoraEditar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMhoraEditar.setText("Asignar/editar");
        jMhoraEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMhoraEditarActionPerformed(evt);
            }
        });
        jMhora.add(jMhoraEditar);

        jMenuBar1.add(jMhora);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/payment_card.png"))); // NOI18N
        jMenu1.setText("Pagos");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem1.setText("Imprimir ficha de pago");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_square.png"))); // NOI18N
        jMsalir.setText("Salir");
        jMsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMsalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMprofAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMprofAnadirActionPerformed
        NuevoProf nue=new NuevoProf();
        jDesktopPane1.add(nue);
        nue.toFront();
        nue.setVisible(true);
    }//GEN-LAST:event_jMprofAnadirActionPerformed

    private void jMalumAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumAnadirActionPerformed
        Nuevoalu nal=new Nuevoalu();
        jDesktopPane1.add(nal);
        nal.toFront();
        nal.setVisible(true);
    }//GEN-LAST:event_jMalumAnadirActionPerformed

    private void jMclasNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMclasNuevaActionPerformed
        NuevaClase nclas=new NuevaClase();
        jDesktopPane1.add(nclas);
        nclas.toFront();
        nclas.setVisible(true);
    }//GEN-LAST:event_jMclasNuevaActionPerformed

    private void jMprofVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMprofVerActionPerformed
        busqueda busq=new busqueda();
        jDesktopPane1.add(busq);
        busq.toFront();
        busq.setVisible(true);
    }//GEN-LAST:event_jMprofVerActionPerformed

    private void jMalumVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumVerActionPerformed
        VerAlu vera=new VerAlu();
        jDesktopPane1.add(vera);
        vera.toFront();
        vera.setVisible(true);
    }//GEN-LAST:event_jMalumVerActionPerformed

    private void jMclasVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMclasVerActionPerformed
        VerClas verc=new VerClas();
        jDesktopPane1.add(verc);
        verc.toFront();
        verc.setVisible(true);
    }//GEN-LAST:event_jMclasVerActionPerformed

    private void jMclasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMclasEliminarActionPerformed
        ElimClas elic=new ElimClas();
        jDesktopPane1.add(elic);
        elic.toFront();
        elic.setVisible(true);
    }//GEN-LAST:event_jMclasEliminarActionPerformed

    private void jMsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMsalirMouseClicked
        Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿Deseas cerrar el sistema?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        else{
        }
    }//GEN-LAST:event_jMsalirMouseClicked

    private void jMalumClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumClasesActionPerformed
        BuscarAlu busqalu=new BuscarAlu();
        jDesktopPane1.add(busqalu);
        busqalu.toFront();
        busqalu.setVisible(true);
    }//GEN-LAST:event_jMalumClasesActionPerformed

    private void jMhoraEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMhoraEditarActionPerformed
        VerClas verc=new VerClas();
        jDesktopPane1.add(verc);
        verc.show();
    }//GEN-LAST:event_jMhoraEditarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        busfich busq=new busfich();
        jDesktopPane1.add(busq);
        busq.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMalum;
    private javax.swing.JMenuItem jMalumAnadir;
    private javax.swing.JMenuItem jMalumClases;
    private javax.swing.JMenuItem jMalumVer;
    private javax.swing.JMenu jMclas;
    private javax.swing.JMenuItem jMclasEliminar;
    private javax.swing.JMenuItem jMclasNueva;
    private javax.swing.JMenuItem jMclasVer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMhora;
    private javax.swing.JMenuItem jMhoraEditar;
    private javax.swing.JMenu jMprof;
    private javax.swing.JMenuItem jMprofAnadir;
    private javax.swing.JMenuItem jMprofVer;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables

    public void verpr() {
            jDesktopPane1.add(verpr);
            verpr.toFront();
            verpr.setVisible(true);
    }
    
    
}
