/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alumnos;

import Conexion.conexion;
import Frames.Inicio;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author obedn
 */
public class BuscarAlu extends javax.swing.JInternalFrame {
    AsigAlu asig=new AsigAlu();
    /**
     * Creates new form BuscarAlu
     */
    public BuscarAlu() {
        initComponents();
        tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Buscador de alumno");

        jLabel2.setText("Nombre");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String nombre;
        int seleccion=jTable1.rowAtPoint(evt.getPoint());
        String nomb = String.valueOf(jTable1.getValueAt(seleccion, 0));ResultSet rs;
        jLabel1.setText(nomb);
        Connection conn;
        conn = conexion.getConnection();
        String sql = "SELECT * FROM alumnos WHERE nombre LIKE '%"+nomb+"%'";
        try{
            Statement stmt = conn.createStatement();
            rs=stmt.executeQuery(sql);
            rs.beforeFirst();
            rs.next();
            nombre=rs.getString(2);
            asig.jLabel2.setText(nombre);
            combos();
            Inicio.jDesktopPane1.add(asig);
            asig.toFront();
            asig.setVisible(true);
            dispose();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        tabla();
    }//GEN-LAST:event_jTextField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void tabla() {
        String nomb=jTextField1.getText();
        DefaultTableModel modelotabla=new DefaultTableModel();
        ResultSet rs=conexion.getTabla("SELECT * FROM alumnos WHERE nombre LIKE '%"+nomb+"%'");
        modelotabla.setColumnIdentifiers(new Object[]{"Nombre"});
        try{
            while(rs.next()){
                modelotabla.addRow(new Object[]{rs.getString("nombre")});
            }
            jTable1.setModel(modelotabla);
        }catch(Exception e){
            System.out.println(e);
        }
    }

    private void combos() {
        String clases;
        ResultSet rs;
            Connection conn;
            conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String a=jLabel1.getText();
            String sql = "SELECT * FROM alumnos WHERE nombre ='"+a+"'";
            try{
                Statement stmt = conn.createStatement();
                rs=stmt.executeQuery(sql);
                rs.beforeFirst();
                rs.next();
                clases=rs.getString(4);
                String[] clas=clases.split(",");
                asig.jComboBox1.setSelectedItem(clas[0]);
                asig.jComboBox2.setSelectedItem(clas[1]);
                asig.jComboBox3.setSelectedItem(clas[2]);
                asig.jComboBox4.setSelectedItem(clas[3]);
                asig.jComboBox5.setSelectedItem(clas[4]);
                asig.jComboBox6.setSelectedItem(clas[5]);
                asig.jComboBox7.setSelectedItem(clas[6]);
            }catch(Exception e){
                System.out.println(e);
            }
    }
}
